app/newsletters/forms.py
"""
this forms 
allow user to gel all GR newsletters and newsletters links 
"""
from flask_wtf import FlaskForm
from wtforms import SelectMultipleField, StringField, SubmitField, SelectField
from wtforms.validators import DataRequired

class Available_newsletters(FlaskForm):
    available_newsletters = SelectField(\
        'Доступные письма и черновики')
    submit = SubmitField('Получить список ссылок в письме')

class Available_links(FlaskForm):
    available_links = SelectMultipleField('Доступные ссылки в выбранном письме', choices=[])
    submit = SubmitField('Обернуть выбранные ссылки и отправить в GetResponse')

class Api_key(FlaskForm):
    key = StringField('API ключ', validators=[DataRequired()])
    submit = SubmitField('Получить список доступных писем и черновиков')

app/analytics/__init__.py
"""
this blueprint handle 
every needs related to visitors segmentations
based on behavior on customer site
"""
from flask import Blueprint

bp = Blueprint('analytics', __name__)

from app.analytics import routes

app/analytics/routes.py
"""
analytics routes
"""

from flask import Blueprint, render_template, request, redirect, url_for, flash, abort, current_app
from flask_login import login_required, current_user
from app.models import User,\
                       Integration,\
                       SavedSearch
from app import db
from app.analytics import bp
import requests
from app.analytics.utils import current_user_own_integration, \
                                create_url_for_query, \
                                send_request_to_clickhouse, \
                                request_ch_for_initial_data, \
                                build_df_from_CH_response, \
                                translate_form_dict_to_query, \
                                validate_external_segment_name, \
                                validate_analytics_form, \
                                build_analytics_search_json
from app.grhub.grmonster import GrMonster
import traceback
from pprint import pprint
import pandas as pd
from app.analytics.forms import AnalyticsBar, Filters
from collections import defaultdict
from io import StringIO
import base64
import urllib.parse
import numpy as np
import concurrent.futures
import binascii
from app.analytics.analytics_consts import COLUMNS, INITIAL_QUERY,INITIAL_QUERY_COLUMNS
from app.utils import get_metrika_goals
import json
from flask import jsonify

# send search contacs to GR campaing by http API
@bp.route('/analytics/send_search_contacts/<integration_id>', methods=['POST'])
@current_user_own_integration
@login_required
def send_search_contacts(integration_id):
    integration = Integration.query.filter_by(id = integration_id).first_or_404()
    try:
        current_user.launch_task('send_search_contacts_to_gr', \
                                    'Загрузка контактов в GR, прогресс: ', \
                                    request.form['contactsList'].split(','), \
                                    request.form['campaignId'],\
                                    integration.api_key,\
                                    current_user.id)
        db.session.commit()
    except:
        return abort(404)
    return {'status':'<200>'}

# send search contacs to GR campaing by FTP
@bp.route('/analytics/ftp_search_contacts/<integration_id>', methods=['POST'])
@current_user_own_integration
@login_required
def ftp_search_contacts(integration_id):
    if not validate_external_segment_name(request.form['external_name']):
        abort(404)
    form_dic=request.form.to_dict(flat=False)
    query = translate_form_dict_to_query(form_dic,integration_id)
    query_url = create_url_for_query(query,current_user.crypto)
    integration = Integration.query.get(integration_id)
    # if saved search not present create it else rewrite it query
    if request.form['external_name'] not in [saved_search.name for saved_search in integration.saved_searched]:        
        print('new saved_search')
        saved_search = SavedSearch(name=request.form['external_name'], \
                                    ch_query = query_url, \
                                    integration_id=integration_id)
        db.session.add(saved_search)
        db.session.commit()
        method = 'insert'
    else:
        print('saved_searche already exists')
        saved_search = [saved_search for saved_search in integration.saved_searched \
                            if saved_search.name == request.form['external_name']][0]
        saved_search.ch_query = query_url
        db.session.commit()
        method = 'replace'
    grmonster = GrMonster(integration.api_key,\
                          ftp_login = integration.ftp_login, \
                          ftp_pass = integration.ftp_pass)
    try:
        current_user.launch_task('send_search_contacts_to_gr_ftp', \
                                    'Загрузка контактов в GR FTP, прогресс: ', \
                                    request.form['contactsList'].split(','), \
                                    request.form['external_name'],\
                                    method,\
                                    integration,\
                                    current_user.id)
        db.session.commit()
    except Exception as err:
        print(err)
        abort(404)
    return {'status':'<200>'}

# this route hande POST new GR campaign by http API
@bp.route('/analytics/create_gr_campaign/<integration_id>', methods=["POST"])
@current_user_own_integration
@login_required
def create_gr_campaign_route(integration_id):
    integration = Integration.query.filter_by(id = integration_id).first_or_404()
    grmonster = GrMonster(api_key = integration.api_key, callback_url=integration.callback_url)
    grmonster.create_gr_campaign(request.form['gr_campaign_name'])
    return '<200>'

# this route handle initial analytics page call
# make first request to CH and GR to get initial integration data
# like dates ranges, GR campaigns and YM goals
# TODO need refactor
@bp.route('/analytics/<integration_id>', methods = ['GET', 'POST'])
@login_required
@current_user_own_integration
def generate_values(integration_id):
    form = AnalyticsBar()
    filters_form = Filters()
    integration = Integration.query.filter_by(id=integration_id).first_or_404()
    initial_response_raw =request_ch_for_initial_data(current_user.crypto, integration_id, INITIAL_QUERY)
    if not initial_response_raw.ok:
        flash('Ошибка или создание интеграции не завершено')
        return redirect(url_for('main.user_integrations'))
    inital_data_df = build_df_from_CH_response(initial_response_raw, INITIAL_QUERY_COLUMNS)
    goals = get_metrika_goals(integration.metrika_key,integration.metrika_counter_id)
    grmonster = GrMonster(integration.api_key)
    gr_campaigns = grmonster.get_gr_campaigns()
    saved_searches = integration.saved_searched.all()      
    # get unique values for every choice
    uniqueOpSys = inital_data_df['OperatingSystem'].unique()
    uniqueRegCyt = inital_data_df['RegionCity'].unique()
    uniqueURL = inital_data_df['cutQueryString(URL)'].unique()
    uniquePh = inital_data_df['MobilePhone'].unique()
    uniquePhM = inital_data_df['MobilePhoneModel'].unique()
    uniqueBro = inital_data_df['Browser'].unique()
    # get initial summary data
    start_date = inital_data_df['Date'].min()
    end_date = inital_data_df['Date'].max()
    total_unique_emails = len(inital_data_df['mxm'].unique())
    # Adding choices to the forms
    form.OperatingSystem.choices = list(zip(uniqueOpSys,uniqueOpSys))
    form.RegionCity.choices = list(zip(uniqueRegCyt,uniqueRegCyt))
    form.URL.choices = list(zip(uniqueURL,uniqueURL))
    form.GoalsID.choices = goals
    form.MobilePhone.choices = list(zip(uniquePh,uniquePh))
    form.MobilePhoneModel.choices = list(zip(uniquePhM,uniquePhM))
    form.Browser.choices = list(zip(uniqueBro,uniqueBro))
    return render_template('analytics.html',\
                            form=form,\
                            filters_form=filters_form,\
                            gr_campaigns = gr_campaigns,\
                            saved_searches = saved_searches,\
                            start_date=start_date,\
                            end_date=end_date,\
                            total_unique_emails=total_unique_emails,
                            integration_name=integration.integration_name)

# this route handle analytics form send
# here we make calls to CH to get visitors
# that meet conditions choosed by user in /analytics/<integration_id> route 
@bp.route('/analytics/getdata', methods = ['GET','POST'])
@login_required
def process_values():
    # TODO check if current_us owns integration
    #geting the dict from the form
    integration_id = request.form["integration_id"]
    form_dic=request.form.to_dict(flat=False)
    query = translate_form_dict_to_query(form_dic,integration_id)
    query_url = create_url_for_query(query,current_user.crypto)
    ch_response = send_request_to_clickhouse(query_url)
    analytics_search_df = build_df_from_CH_response(ch_response, COLUMNS)
    json_to_return = build_analytics_search_json(analytics_search_df)
    return json_to_return

app/metrika/__init__.py
"""
this bp handles every need
related to email marketing performance analysis
"""

from flask import Blueprint

bp = Blueprint('metrika', __name__)

from app.metrika import routes

app/metrika/routes.py
"""
metrika (performance analytics) routs
"""

import json
from datetime import datetime, timedelta
from flask import render_template, request, redirect, url_for, flash, abort, current_app
from flask_login import login_required, current_user
from app.models import User, Integration
from app import db
from app.metrika import bp
from app.clickhousehub.clickhouse_custom_request import made_url_for_query,request_clickhouse
from app.metrika.secur import current_user_own_integration
from app.grhub.grmonster import GrMonster
from app.utils import decode_this_string,encode_this_string
from operator import itemgetter
from app.metrika.metrika_sql_queries import TIME_SERIES_QUERY, VISITS_RAW_QUERY,TIME_SERIES_DF_COLUMNS, COLUMNS
from app.main.utils import check_if_input_legal
from app.metrika.utils import request_min_max_visits_dates, get_df_from_CH
from app.utils import get_metrika_goals
from app.metrika.metrika_report import MetrikaReport
from app.analytics.utils import current_user_own_integration

# this route handle building convesion and timeseries data
# based on date and goals filters set up by user
@bp.route('/metrika/<integration_id>/get_data')
@login_required
@current_user_own_integration
def metrika_get_data(integration_id):
    integration = Integration.query.filter_by(id=integration_id).first_or_404()
    # retrieve args and validate them
    request_start_date = request.args.get('start_date')
    request_goals = request.args.get('goals') # TODO: validate goals
    if not check_if_input_legal(request_start_date,request_goals):
        print('Illigal user input')
        abort(404)
    goals_filter_array=[]
    if request_goals:
        # list + map because CH store GoalsId as ints
        # so we need ints too perform CH functions on it
        goals_filter_array=list(map(int, request_goals.split(',')))
    # TODO integrate it to class like metrika report
    time_series_goals_df = get_df_from_CH(current_user.crypto, integration_id, TIME_SERIES_QUERY,goals_filter_array,request_start_date,TIME_SERIES_DF_COLUMNS)
    clientid_convers_df = get_df_from_CH(current_user.crypto, integration_id, VISITS_RAW_QUERY,goals_filter_array,request_start_date,COLUMNS)
    # bad outside target unit logic :(
    if request_goals:
        clientid_convers_df = clientid_convers_df[clientid_convers_df['Всего целей выполнено']!=0]
    # generate report based on CH data
    metrika_report = MetrikaReport(clientid_convers_df, time_series_goals_df)
    metrika_report.load_email_visits_table()
    grmonster = GrMonster(api_key=integration.api_key, callback_url=integration.callback_url)
    broadcast_messages_since_date_subject_df = grmonster.get_broadcast_messages_since_date_subject_df(request_start_date)
    metrika_report.load_time_series(broadcast_messages_since_date_subject_df)
    metrika_report.load_pie()
    metrika_report.load_summary()
    return metrika_report.report_json


# init metrika page view
# it collectes data ranges data from CH and goals from YM
@bp.route('/metrika/<integration_id>', methods = ['GET'])
@login_required
@current_user_own_integration
def metrika(integration_id):
    integration = Integration.query.filter_by(id=integration_id).first_or_404()
    #request init info
    response, min_date_text, max_date_text = request_min_max_visits_dates(current_user.crypto,integration_id)
    if not response.ok:
        flash('Ошибка или создание интеграции не завершено')
        return redirect(url_for('main.user_integrations'))
    # get goals
    counter_id = integration.metrika_counter_id
    metrika_key = integration.metrika_key
    goals = get_metrika_goals(metrika_key,counter_id)

    return render_template(\
        'metrika.html',\
        min_date=min_date_text,\
        max_date=max_date_text,\
        integration_name=integration.integration_name,\
        integration_id=integration_id,\
        goals=goals)

# this route handles GR subscribe callback 
# TODO looks like it should be in MAIN bp
@bp.route('/metrika/callback_add_custom_field/<identificator>', methods = ['GET','POST'])
def callback_add_custom_field(identificator):
    identificator_decoded=decode_this_string(identificator)
    user_id, integration_id = itemgetter(0, 1)(identificator_decoded.split('-'))
    integration = Integration.query.filter_by(id = int(integration_id)).first()
    user = User.query.filter_by(id = int(user_id)).first()
    action = request.args.get('action')
    if user == integration.user and action == 'subscribe':
        gr_monster = GrMonster(api_key=integration.api_key, callback_url=integration.callback_url)
        contact_email = request.args.get('contact_email')
        contact_id = request.args.get('CONTACT_ID')
        gr_monster.set_hash_email_custom_field_id()
        gr_monster.upsert_hash_field_for_contact(contact_id,encode_this_string(contact_email))

    return redirect(url_for('main.index'))

app/newsletters/__init__.py
"""
this bp 
handle user needs to 
fast wrap all links in GR newsletter
into hashmetrika custom field param
"""
from flask import Blueprint

bp = Blueprint('newsletters', __name__)

from app.newsletters import routes

app/newsletters/routes.py
"""
wrapping GR newsletter links routes
most call come from analytics js
"""

from flask import render_template, redirect, url_for, request, flash, abort
from flask_login import login_required, current_user
from app.newsletters import bp
from app.newsletters.forms import Available_newsletters, \
                                  Available_links, \
                                  Api_key
from app.newsletters.gr_requests import get_newsletters_names,\
                                        get_newsletters_links_for_newsletterId, \
                                        gr_post_wrapped_newsletter
import datetime

# main page view
@bp.route('/newsletters')
@login_required
def newsletters():
    available_newsletters_form = Available_newsletters()
    available_links_form = Available_links()
    api_key_form = Api_key()
    return render_template('newsletters.html',\
        available_newsletters_form=available_newsletters_form,\
        available_links_form=available_links_form,\
        api_key_form=api_key_form)

@bp.route('/get_newsletters', methods=['POST'])
@login_required
def get_newsletters():
    key = request.json
    response = get_newsletters_names(key)
    return response


@bp.route('/post_wrapped_newsletter', methods=['POST'])
@login_required
def post_wrapped_newsletter():
    timestamp= datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    key, newsletter_id, links = request.json['key'], \
                                request.json['newsletterId'], \
                                request.json['links']
    try:
        gr_post_wrapped_newsletter(key, newsletter_id, links)
    except ConnectionRefusedError as err:
        current_user.send_message(f'{str(timestamp)} : ошибка создания письма в GR')
        current_user.add_notification('unread_message_count', current_user.new_messages())
        abort(300)
    else:
        # TODO add newsletter name for user message notif
        current_user.send_message(f'{str(timestamp)} : Черновик с обернутыми ссылками создан в GR')
        current_user.add_notification('unread_message_count', current_user.new_messages())

    return '<200>'

@bp.route('/get_newsletter_links', methods=['POST'])
@login_required
def get_newsletters_links():
    key = request.json['key']
    newsletterId = request.json['newsletterId']
    response = get_newsletters_links_for_newsletterId(key,newsletterId)
    return response

app/templates/_integration.html
<tr id='{{integration.id}}'>
    <td class="td-integration-name">
       {{integration.integration_name}}
    </td>

  <!--  <td class="integration-justlink">
      <a class="btn grmax-justlink"
      href="{{url_for('main.edit_integration', integration_id = integration.id) }}"
      role="button">
        Настроить интеграцию
      </a>
    </td> -->
    <td class="integration-justlink">
      <a class="btn grmax-justlink"
      href="{{url_for('metrika.metrika', integration_id = integration.id) }}"
      role="button">
        Конверсия
      </a>
    </td>
    <td class="integration-justlink">
      <a class="btn grmax-justlink"
      href="{{url_for('analytics.generate_values', integration_id = integration.id) }}"
      role="button">
        Аналитика
      </a>
    </td>
    <!-- <td class="integration-justlink">
      <a class="btn grmax-justlink" href="javascript:delete_integration('{{ integration.id }}')">{{ ('Удалить интеграцию') }}</a>
    </td>-->
    <td class="integration-dotes">
      <div class="show_settings">
        <i class="fa fa-ellipsis-v fa-lg"  aria-hidden="true"></i>
        <div class="integration-settings">
          <ul>
            <li>
              <a class="btn grmax-justlink"
            href="{{url_for('main.edit_integration', integration_id = integration.id) }}"
            role="button">Настроить</a>
            </li>
            <li>
              <a class="btn grmax-justlink" href="javascript:delete_integration('{{ integration.id }}')">{{ ('Удалить') }}</a>
            </li>
          </ul>
        </div>
      </div>
    </td>
</tr>

app/templates/_message.html
<table class="table table-hover">
       <tr>
           <td>
               <span id="message{{ message.id }}">{{ message.body }}</span>
           </td>
       </tr>
     </table>

app/templates/after_analytics.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block app_content %}
Свойства:

hello!

Действия:



{% endblock %}

app/templates/base.html
<!-- templates/base.html -->
{% extends 'bootstrap/base.html' %}


{% block head %}
{{ super() }}
<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js">
</script>
<script type="text/javascript" src='{{url_for("static",filename="js/google_charts.js")}}'>
</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/react/0.13.2/react.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/react/0.13.2/JSXTransformer.js"></script>

<link id="load-css-0" rel="stylesheet" type="text/css" href="https://www.gstatic.com/charts/48.1/css/core/tooltip.css">
<link id="load-css-1" rel="stylesheet" type="text/css" href="https://www.gstatic.com/charts/48.1/css/util/util.css">
<link id="load-css-1" rel="stylesheet" type="text/css" href='{{url_for("static",filename="css/styles.css")}}'>
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700%7CRoboto:300,400,500,700&amp;subset=latin,latin" media="all">
<script src="https://use.fontawesome.com/79cfbb194f.js"></script>
<!-- Matomo -->
<script type="text/javascript">
  var _paq = window._paq = window._paq || [];
  /* tracker methods like "setCustomDimension" should be called before "trackPageView" */
  _paq.push(['trackPageView']);
  _paq.push(['enableLinkTracking']);
  (function() {
    var u="//magic-dev.ru/analytics/";
    _paq.push(['setTrackerUrl', u+'matomo.php']);
    _paq.push(['setSiteId', '1']);
    var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
    g.type='text/javascript'; g.async=true; g.src=u+'matomo.js'; s.parentNode.insertBefore(g,s);
  })();
</script>
<!-- End Matomo Code -->

{% endblock %}
{% block title %}
        {% if title %}{{ title }} - GetResponse Analytics{% else %}GetResponse Analytics{% endif %}
{% endblock %}

{% block navbar %}
  <nav class="navbar navbar-default grmax-navbar">
      <div class="container center">
      <ul class="nav navbar-nav navbar-left">
        <li>
          <a class="navbar-brand" href="{{ url_for('main.index') }}">
          <img src="{{ url_for('static', filename='img/logo.png') }}" height="32px" alt="Logo">
          </a>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        {% if current_user.is_anonymous %}
        <li>
          <a href="{{ url_for('auth.login') }}" class="navbar-item">
            Войти
          </a>
        </li>
        <li>
        <a href="{{ url_for('auth.register') }}" class="navbar-item">
            Зарегистрироваться
        </a>
        </li>
        {% endif %}
        {% if current_user.is_authenticated %}
        <li id="navbar-profile">
        <a href="" class="navbar-item" id='navbar-profile-link'>
             Инструменты
        </a>
        <div class="navbar-submenu navbar-submenu-profile">
          <ul>
            <li><a href="{{url_for('main.user_integrations')}}" class="show-integration">Показать интеграции</a></li>
            <li><a href="{{url_for('main.link_creation')}}" class="create-link">Создать ссылку</a></li>
            <li><a href="{{url_for('newsletters.newsletters')}}" class="create-letter">Создать письмо</a></li>
            <li><a href="{{url_for('main.gr_init')}}" class="gr-init">Инициация GetResponse аккаунта</a></li>
          </ul>
        </div>
        </li>
        <li>
            <a href="{{ url_for('main.messages') }}">
                {{ ('Уведомления') }}
                {% set new_messages = current_user.new_messages() %}
                <span id="message_count" class="badge"
                      style="display: {% if new_messages %}inline-block
                                         {% else %}none {% endif %};">
                    {{ new_messages }}
                </span>
            </a>
        </li>
        {% if current_user.email == 'george1@mail.ru' %}
        <li>
        <a href="{{ url_for('main.admin') }}" class="navbar-item">
            Админка
        </a>
        </li>
        {% endif %}
        <li>
        <a href="{{ url_for('main.documentation') }}" class="navbar-item">
            Документация
        </a>
        </li>
        <li>
        <a href="{{ url_for('main.profile') }}" class="navbar-item">
            {{current_user.email}}
        </a>
        </li>
        <li>
        <a href="{{ url_for('auth.logout') }}" class="navbar-item">
            Выйти
        </a>
        </li>
        {% endif %}
      </ul>
    </div>
</nav>
        {% endblock %}
        {% block content %}
            <div class="container grmax-container">
                {% with messages = get_flashed_messages() %}
                {% if messages %}
                    {% for message in messages %}
                    <div class="alert alert-info" role="alert">{{ message }}</div>
                    {% endfor %}
                {% endif %}
                {% endwith %}

                {% if current_user.is_authenticated %}
                   {% with tasks = current_user.get_tasks_in_progress() %}
                   {% if tasks %}
                       {% for task in tasks %}
                       <div class="alert alert-success" role="alert">
                           {{ task.description }}
                           <span id="{{ task.id }}-progress">{{ task.get_progress() }}</span>
                       </div>
                       {% endfor %}
                   {% endif %}
                   {% endwith %}
                {% endif %}

                {# application content needs to be provided in the app_content block #}
                {% block app_content %}{% endblock %}
            </div>
        {% endblock %}

{% block scripts %}
{{ super() }}
<script type="text/javascript" src="{{url_for("static",filename="js/common.js")}}"></script>
<script type="text/jsx" src='{{url_for("static",filename="js/react_table_components.js")}}'></script>
<script>

  {% if current_user.is_authenticated %}
  $(function() {
      var since = 0;
      setInterval(function() {
          $.ajax('{{ url_for('main.notifications') }}?since=' + since).done(
              function(notifications) {
                  for (var i = 0; i < notifications.length; i++) {
                      switch (notifications[i].name) {
                          case 'unread_message_count':
                              set_message_count(notifications[i].data);
                              break;
                          case 'task_progress':
                              set_task_progress(notifications[i].data.task_id,
                                  notifications[i].data.progress);
                              break;
                      }
                      since = notifications[i].timestamp;
                  }
              }
          );
      }, 10000);
  });
  {% endif %}

  function set_message_count(n) {
      $('#message_count').text(n);
      $('#message_count').css('visibility', n ? 'visible' : 'hidden');
  }

     function set_task_progress(task_id, progress) {
         $('#' + task_id + '-progress').text(progress);
     }

    function delete_integration(integration_id){

        $.post('/delete_integration', {
            integration_id : integration_id,
        }).done(function(response) {
            $('#'+integration_id).hide(1500);
        }).fail(function() {
            $('#'+integration_id).show(1500);
            location.reload()
        });
    }
</script>
<script src='{{url_for("static",filename="js/csvExport.js")}}'></script>

<footer class="grmax-footer">
  <div class="shadow"></div>
  <div class="mfooter-info">
    <p class="mfooter-copyright">
      <a class="mfooter-logo" href="/" title="Инструменты для маркетинга от GetResponse"><img src="https://us-as.gr-cdn.com/images/secure-getresponse/global/footer/mini-logo.svg" alt="Инструменты для маркетинга от GetResponse"></a>
      <span class="mfooter-text"> Copyright ©  2020 GetResponse. Email Marketing. Solved<sup>®</sup>. </span>
    </p>
  </div>
</footer>
{% endblock %}

app/templates/create_integration.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block app_content %}
  <div class="row">
    {% if title %} <h2>{{title}}</h2> {% endif %}
      <div class="col-md-4">
          {{ wtf.quick_form(form) }}
          <a class="btn btn-info" href="{{url_for('main.user_integrations')}}">Назад</a>
      </div>
  </div>
{% endblock %}

app/templates/doc_api_key_from_ym.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block app_content %}
<a class="grmax-justlink" href="{{url_for('main.documentation')}}"><i class="fa fa-long-arrow-left" aria-hidden="true"></i> Назад</a>
<div class="container container-doc">
  <h2>Создание API-ключа в Яндекс-метрике</h2>
  <p class="">Для того, чтобы платформа аналитики смогла получить доступ к данным вашего счетчика Яндекс-метрики, нужно получить API-ключ, который вам нужно будет указать при создании интеграции. Ниже предоставляем подробную инструкцию по получению API-ключа</p>
  <ol>
    <li><p>В первую очередь вам нужно зайти на страницу <a href="https://metrika.yandex.ru" class="grmax-blue-link">вашего счетчика</a>, чтобы убедиться, что вы залогинены в системе и имеете доступ к нему.</p></li>
    <li><p>Далее заходим на страницу <a href="https://oauth.yandex.ru/client/new" class="grmax-blue-link">https://oauth.yandex.ru/client/new</a> и создаем новое приложение.<p>
    <p>Вводим любое название приложения, в разделе "платформы" выбираем "Веб-сервисы". Нажимаем на ссылку "Подставить URL для разработки".</p>
    <p class="text-center"><img src="{{ url_for('static', filename='img/doc_api_key_from_ym_1.png') }}"></p>
    <p>В разделе "Доступы" выбираем Яндекс.Метрика и отмечаем пункт "Получение статистики, чтение параметров своих и доверенных счетчиков"</p>
    <p class="text-center"><img src="{{ url_for('static', filename='img/doc_api_key_from_ym_2.png') }}"></p>
    <p>Нажимаем "Создать приложение" в самом низу страницы.</p>
    </li>
    <li><p>Видим страницу с данными, необходимыми для получения ключа. <strong>ВНИМАНИЕ</strong> - страницу пока не закрываем!!!</p>
    <p class="text-center"><img src="{{ url_for('static', filename='img/doc_api_key_from_ym_3.png') }}"></p>
    </li>
    <li><p>Формируем ссылку вида:</p>
      <p><code>https://oauth.yandex.ru/authorize?response_type=token&client_id=<идентификатор приложения></code></p>
      <p>Здесь <идентификатор приложения> - это ID из предыдущего пункта.</p>
    </li>
    <li><p>Заходим по ссылке, сформированной в предыдущем пункте и видим примерно такую страницу:</p>
      <p class="text-center"><img src="{{ url_for('static', filename='img/doc_api_key_from_ym_4.png') }}"></p>
      <p>Код, который вы видите в центре страницы - это и есть необходимый нам API-ключ. Вам нужно его скопировать (лучше сохранить куда-нибудь, чтобы в будущем не проходить процедуру получения ключа заново) и  указать при создании интеграции.</p>
    </li>
  </ol>

</div>

{% endblock %}

app/templates/documentation.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block app_content %}

<div class="container container-documentation">
  <ul>
    <li><a href="{{ url_for('main.api_key_from_ym') }}" class="grmax-blue-link">Как получить API-ключ для Яндекс-метрики</a>
    </li>
  </ul>

</div>



{% endblock %}